title: <p align="center"> Pooja Kulkarni </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://github.com/PoojaKulkarni1391">GitHub</a>
  
  <br>   
  I'm working on Data Science, Machine learning & NLP related problems.
  I have 10 years of experience in MSBI, SQL, DW and ETL processing.
  Working with Atos Syntel as MSBI Developer.
  Worked with in Wells Fargo, Deloitte USI and Cognizant.
  <br>
  </p>




theme: jekyll-theme-minimal
